# Étape 1 : compiler React
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# En prod, /api est relatif — nginx redirige vers l'API
ENV VITE_API_URL=/api

RUN npm run build

# Étape 2 : servir avec nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]